version: '3.8'
services:
  db:
    image: postgres:17  # Если это доступно, иначе используйте актуальную версию, например, 15
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db  # Используйте 'db' для подключения через Docker
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_PASSWORD: 0000
      DB_NAME: wallet_db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
